import BackgroundShell from "@/src/components/BackgroundShell";
import AppProviders from "@/src/providers/AppProviders";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Gajraj_One } from "next/font/google";
import "./globals.css";

const gajrajOne = Gajraj_One({
  subsets: ["latin"],
  weight: "400",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full overflow-hidden antialiased`}
    >
      <body className={`${gajrajOne.className} flex h-full flex-col overflow-hidden`}>
        <AppProviders>
          <BackgroundShell>{children}</BackgroundShell>
        </AppProviders>
      </body>
    </html>
  );
}
